### ISSUE TITLE
Paged view - page pairings should taken into account for line breaks

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/iiifManifestLayouts#52]

**Comment by aeschylus** [comment]
@mejackreed Can you help take linebreaks into account? I think all of the problem is handled in one the [fixedHeightAlign](https://github.com/aeschylus/iiifManifestLayouts/blob/master/src/manifestLayout.js#L247-L303) function. The strategy was that I track remaining space in the line (in this case horizontal space), and if the remaining width is less than the width of the element, I break to a new line. The line number and x position are passed back to the outer function of the method and attached as data to the canvas and frame objects. Because height is fixed, the y component is always the line number multiplied by the chosen height. it helps to start reading it from the [return statement at the bottom](https://github.com/aeschylus/iiifManifestLayouts/blob/master/src/manifestLayout.js#L295-L302), to see how these inner functions are used.

Right-to-left changes signs (we start from the right instead of left, subtracting as we go). The two-page break should be as simple as making sure that the quantity being used in the subtraction in the combined width of both pages in a spread, and skipping down to a new line early, but I have had some difficulty getting it to work. Could use some help debugging it while I'm fixing the image bugs.
